# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{atomfeed}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{nil paulownia}]
  s.date = %q{2011-12-22}
  s.description = %q{parsing and generating atom feed}
  s.email = %q{hisary+dev@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "atomfeed.gemspec",
    "lib/atom/category.rb",
    "lib/atom/date.rb",
    "lib/atom/elements.rb",
    "lib/atom/entry.rb",
    "lib/atom/feed.rb",
    "lib/atom/link.rb",
    "lib/atom/meta.rb",
    "lib/atom/person.rb",
    "lib/atom/rexml.rb",
    "lib/atom/text.rb",
    "lib/atomfeed.rb",
    "spec/atom_content_spec.rb",
    "spec/atom_date_spec.rb",
    "spec/atom_entries_spec.rb",
    "spec/atom_entry_spec.rb",
    "spec/atom_feed_spec.rb",
    "spec/atom_link_spec.rb",
    "spec/atom_links_spec.rb",
    "spec/atom_spec.rb",
    "spec/atomfeed_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/files.rb",
    "spec/support/files/load.xml",
    "spec/support/files/write_compared.xml"
  ]
  s.homepage = %q{http://github.com/paulownia/atomfeed}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Atom Feed Parser and Generator}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

